### ISSUE TITLE
Unable to see co-ordinates in Tour Stops.

### ISSUE THREAD

**Issue by Anterotesis** [CPHDH/placepress#10]
Using PlacePress 1.2.3

In the Block Editor, visual mode, there is no way to se the co-ordinates one has entered for the 'Tour Stop' blocks.

Although there is the text 'View on Map' when one mouseovers the default image, and the cursor icon changes to indicate a clickable link, when hoverin gover the point marker of the default tour stop image, on clickng nothing happens.

There is no other display of what co-ordinates have been input. Clicking 'Set Co-ordinates' after one has input co-ordinates does not show the 'old' co-ordinates. Similarly, there is no record of the co-ordinates in the 'Tour' or 'Block' properie lists in the side menu.

(Note: it is possible to see the co-ordinates by going to the code view.)

**Comment by csudigitalhumanities** [comment]
The coordinates are shown in the map infowindow (popup). The screenshot below is from a pending release so it differs a little from what you'll see but only slightly.

<img width="1020" alt="Screen Shot 2021-03-18 at 11 10 06 AM" src="https://user-images.githubusercontent.com/11981679/111649218-8b9eea00-87da-11eb-9689-6e0227239514.png">

**Comment by Anterotesis** [comment]
Is that for a 'Location' or for a 'Tour stop'?

I'm not getting anything like that when building my tours. See screenshot.

![Screenshot 2021-03-18 at 15 20 40](https://user-images.githubusercontent.com/8408004/111650962-bb131e00-87fd-11eb-91d5-d32f04efddaf.png)

**Comment by Anterotesis** [comment]
Is that for a 'Location' or for a 'Tour stop'?

I'm not getting anything like that when building my tours. See screenshot.

(Edited for better screenshot.)

![Screenshot 2021-03-18 at 15 24 46](https://user-images.githubusercontent.com/8408004/111651446-2361ff80-87fe-11eb-9a28-10b2e1f41d10.png)

**Comment by csudigitalhumanities** [comment]
If you click the "Set Coordinates" button to reveal the map, that's where you should see it in the Tour Stop block.

**Comment by Anterotesis** [comment]
Okay, that works for me.
Thanks v. much.
Closing this issue.
