### ISSUE TITLE
Feature Request: Allow full width pages on themes with sidebars.

### ISSUE THREAD

**Issue by Anterotesis** [CPHDH/placepress#11]
Using PlacePress 1.2.3.

In the WP Block Editor (and the classic editor), when editing a page, there is a menu entry 'Page Attributes', that allows one to choose between Default Template, Front Page Template, and Full width page template, no sidebar.

This last option would be very useful to choose, especially for PlacePress Tours, when one has set an itinery, and does not want to distract from that.

**Comment by csudigitalhumanities** [comment]
I'll add `page-attributes` to the `supports` array for `register_post_type()` in the next release. As far as I can see, all that's going to do is add a metabox for ordering the post, though it may vary by theme. Looks like template choices, setting the homepage, etc. are only an option on pages (not posts or custom post types, i.e. locations and tours).

<img width="279" alt="Screen Shot 2021-03-18 at 9 31 34 AM" src="https://user-images.githubusercontent.com/11981679/111634345-cd289880-87cc-11eb-89d0-9c7432b919dd.png">

**Comment by csudigitalhumanities** [comment]
Quick update. You can enable the use of your theme templates by adding the post type slugs to an existing template as shown below (pending the next update).

```
<?php
/**
 * Template Name: Full Width Template
 * Template Post Type: post, page, locations, tours
```
